#! /bin/sh

echo ${TIMEZONE} > /etc/timezone
[ -f /etc/flexget/config.yml ] || cat <<EOF >> /etc/flexget/config.yml
web_server:
  bind: 0.0.0.0
  port: 3539

tasks:
  task_name:
    rss: http://example.com
    series:
      - name

schedules: no

EOF

echo "Login for flexget: flexget:${FG_PASSWORD}"
echo "Login for transmission: ${TR_USERNAME}:${TR_PASSWORD}"

flexget -c /etc/flexget/config.yml --loglevel ${FG_LOG_LEVEL} web passwd ${FG_PASSWORD} > /dev/null
flexget -c /etc/flexget/config.yml --loglevel ${FG_LOG_LEVEL} daemon start --autoreload-config &

mkdir -p /var/lib/transmission/watch &> /dev/null

transmission-daemon \
  --foreground \
  --config-dir /etc/transmission \
  --port 9091 \
  --peerport 51413 \
  --auth \
  --username ${TR_USERNAME} \
  --password ${TR_PASSWORD}
