#! /bin/sh

# Requested by transmission:
sysctl net.core.rmem_max=4194304
sysctl net.core.wmem_max=1048576

ln -f -n -s /usr/share/zoneinfo/"${TIMEZONE}" /etc/localtime
echo "${TIMEZONE}" > /etc/timezone

[ -f /etc/flexget/config.yml ] || cat <<EOF >> /etc/flexget/config.yml
web_server:
  bind: 0.0.0.0
  port: 3539

tasks:
  task_name:
    rss: http://example.com
    series:
      - name

schedules: no

EOF

echo "Login for flexget: flexget:${FG_PASSWORD}"
echo "Login for transmission: ${TR_USERNAME}:${TR_PASSWORD}"

flexget -c /etc/flexget/config.yml --loglevel "${FG_LOG_LEVEL}" web passwd "${FG_PASSWORD}" > /dev/null
flexget -c /etc/flexget/config.yml --loglevel "${FG_LOG_LEVEL}" daemon start --autoreload-config &

mkdir -p /var/lib/transmission/watch &> /dev/null

transmission-daemon \
  --foreground \
  --config-dir /etc/transmission \
  --port 9091 \
  --peerport 51413 \
  --auth \
  --username "${TR_USERNAME}" \
  --password "${TR_PASSWORD}" \
  --allowed "${TR_ALLOWED}"
